logger:
  type: "zerolog"
  output: "stdout"
  file_name: "app.log"

jwt_authenticator:
  secret_key: "weather app"
  token_ttl: 86400 # sec

open_weather_map_client:
  api_key: "912b4f7dd14a47be30d28689b0e10c01" # replace with your own api key
  hostname: "https://api.openweathermap.org"
  base_url: "/data/2.5/weather"
  timeout: 10 # sec
  max_idle_conns: 10  # sec
  idle_conn_timeout: 30 # sec

database:
  dsn: "user=sourav password=sourav dbname=sourav host=localhost port=5432 sslmode=disable"
  # replace user , password, dbname with your local db credentials.
